# Generated by Django 2.2.3 on 2019-09-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, null=True)),
                ('feedback', models.CharField(max_length=2000, null=True)),
                ('rating', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
