# Generated by Django 2.2.3 on 2019-09-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_Search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='restaurant_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
